version: "3.9"
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ./env/backend.local.env
    volumes:
      - ../backend/app:/app/app
      - ../appdata:/app/appdata
    ports:
      - "127.0.0.1:8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0 --port 8000
      --reload
    networks: [localnet]
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - ./env/frontend.local.env
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    networks: [localnet]
    depends_on: [backend]
volumes:
  frontend_node_modules:
networks:
  localnet: {}